name: 'Globus Compute Action'
description: 'Execute function on endpoint with provided task inputs.'
inputs:
  client-id:
    description: Globus Client ID to use
    required: true
  client-secret:
    description: Globus Client secret to use
    required: true
  endpoint-uuid:
    description: Globus Compute endpoint UUID to run tasks on
    required: true
  function-uuid:
    description: Function UUID to run on endpoint
    required: true
  args:
    description: Task input args specified as list of arguments
    default: '[]'
  kwargs:
    description: Task input kwargs specified as a dictionary of kwargs
    default: '{}'
outputs:
  result:
    description: Task execution result
runs:
  using: 'node20'
  main: 'index.js'
