name: 'Globus Compute Action'
description: 'Execute function on endpoint with provided task inputs.'
inputs:
  client_id:
    description: Globus Client ID to use
    required: true
  client_secret:
    description: Globus Client secret to use
    required: true
  endpoint_uuid:
    description: Globus Compute endpoint UUID to run tasks on
    required: true
  function_uuid:
    description: Function UUID to run on endpoint
    required: true
  args:
    description: Task input args specified as list of arguments
    default: '[]'
  kwargs:
    description: Task input kwargs specified as a dictionary of kwargs
    default: '{}'
  serialized_inputs:
    description:
      Python serialized tasks inputs. Required when chaining functions together.
    default: ''
outputs:
  output:
    description: Task execution result
runs:
  using: 'node20'
  main: 'dist/index.js'
